### ISSUE TITLE
evolve_model() : index of to_drop (line 211)

### ISSUE THREAD

**Issue by cojette** [JohnNay/datafsm#7]
original:  to_drop <- colnames(data)[-which(names(data) %in% c("period", "outcome"))[nzvs]]

: sometimes NA values are occured(ex) nzvs: 2,3 )

I think this line is  right like below. 

to_drop <- colnames(data)[-which(names(data) %in% c("period", "outcome"))][nzvs]

I wonder it is right. 

Thank you!

**Comment by JohnNay** [comment]
Thank you for your suggestion!  I made that change and also added 
if (length(to_drop) > 0){...} after the code line of interest just in case nothing was returned. 

Please let me know if you run into this error or any other errors again. I appreciate it.

**Comment by cojette** [comment]
Thank you for your fast feedback. 
Now I'm using and customizing your package. If I meet other errors or have opinion, I'll share you again.

**Comment by JohnNay** [comment]
Great. I would be very interested to hear what you end up using the package for!
