### ISSUE TITLE
error in evolve_model()

### ISSUE THREAD

**Issue by salmamess** [JohnNay/datafsm#8]
I am trying to use your package, starting with the example you gave: fake data example.
but i keep having this error with : res<-evolve_model(cdata)

Error in fitness(Pop[i, ], ...) : unused argument (maxfitness = 1)

any idea why this happens? 
thanks.

**Comment by JohnNay** [comment]
are you using the package as it is on GitHub? you can do this easily by running this in R:

install.packages("devtools")
devtools::install_github("JohnNay/datafsm")

If after doing this, you still have an error, please let us know. Thanks!
